car_controller_type: basic
max_num_steps: 25
max_trajs_per_file: 5
multiplier_ids:
- 0.5
- 1
- 1.1
num_runs: 25
safe_trajectory_files:
- /home/ivan/SKD5/skd_python/skd_trajectories/skd_trajectories_db/traj_set_5.json
